version: "3.9"

services:
  ranked-scraper:
    build:
      context: ..
      dockerfile: dockerfiles/ranked/Dockerfile
    env_file:
      - ../.env
    environment:
      - PYTHONUNBUFFERED=1
      # Optionally override output directory inside container
      # - RANKED_OUTPUT_DIR=/app/data/tournaments/ranked_override
    volumes:
      - ../data:/app/data
      - ../src:/app/src:ro
      - ../scripts:/app/scripts:ro
    restart: "no"
    # Example dry-run:
    # command: ["--dry-run", "--skip-existing"]

