MATCH = "MATCH"
GROUP_MEMENTO = "GROUP_MEMENTO"
USER_MEMENTO = "USER_MEMENTO"
MAP = "MAP"
GROUP = "GROUP"
MAP_PREFERENCES = "MAP_PREFERENCES"
WEAPONS = "WEAPONS"

ALL_TABLES = [
    MATCH,
    GROUP_MEMENTO,
    USER_MEMENTO,
    MAP,
    GROUP,
    MAP_PREFERENCES,
    WEAPONS,
]
