SCHEMA = "sendouq_analysis"
MATCH = "match"
GROUP_MEMENTO = "group_memento"
USER_MEMENTO = "user_memento"
MAP = "map"
GROUP = "group"
MAP_PREFERENCES = "map_preferences"
WEAPONS = "weapons"


ALL_TABLES = [
    MATCH,
    GROUP_MEMENTO,
    USER_MEMENTO,
    MAP,
    GROUP,
    MAP_PREFERENCES,
    WEAPONS,
]

AGGREGATE_SCHEMA = "sendouq_aggregate"

AGGREGATE_PAST = "past"
AGGREGATE_CURRENT = "current"
PLAYER_BASE = "_player"
MATCH_BASE = "_match"

AGGREGATE_PLAYER_PAST = AGGREGATE_PAST + PLAYER_BASE
AGGREGATE_MATCH_PAST = AGGREGATE_PAST + MATCH_BASE

AGGREGATE_PLAYER_CURRENT = AGGREGATE_CURRENT + PLAYER_BASE
AGGREGATE_MATCH_CURRENT = AGGREGATE_CURRENT + MATCH_BASE
