name: Build and Run Scraper

on:
#   push:
#     branches:
#       - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    environment: Scraper
    outputs:
      skip: ${{ steps.check_changes.outputs.skip }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_SENDOUQ_SCRAPER_TOKEN }}
          fetch-depth: 0
      
      - name: Check for changes
        id: check_changes
        run: |
          echo "Checking for changes"
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1` 2> /dev/null)
          if [ -z "$LATEST_TAG" ]; then
            echo "No tags found, skipping"
            echo "skip=true" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Latest tag: $LATEST_TAG"
          fi

          CHANGES=$(git diff --name-only $LATEST_TAG HEAD -- 'src/sendouq_analysis')
          if [ -n "$CHANGES" ]; then
            echo "Changes found, running"
            echo "skip=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "No changes found, skipping"
            echo "skip=true" >> $GITHUB_OUTPUT
            exit 0
          fi


  build:
    needs: check
    if: needs.check.outputs.skip == 'false'
    runs-on: ubuntu-latest
    environment: Scraper
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Install Docker
        uses: docker/setup-buildx-action@v1

      - name: Build docker image
        run: docker build -t ${{ github.repository }}:$GITHUB_SHA -f dockerfiles/scrape.dockerfile .

      - name: Authenticate to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 300

      - name: Push docker image to DigitalOcean Container Registry
        run: docker push ${{ github.repository }}:$GITHUB_SHA

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve tfplan \
          -var="postgres_user=$POSTGRES_USER" \
          -var="postgres_password=$POSTGRES_PASSWORD" \
          -var="postgres_host=$POSTGRES_HOST" \
          -var="postgres_port=$POSTGRES_PORT" \
          -var="postgres_db=$POSTGRES_DB"
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          TF_VAR_pvt_key: ${{ secrets.DIGITALOCEAN_SSH_KEY_PRIVATE }}
