name: Run Scraper

on:
  #   schedule:
  #     - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    environment: Scraper
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: terraform/scraper
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/scraper
        run: |
          terraform plan -out=tfplan -input=false
        env:
          TF_VAR_do_token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          TF_VAR_pvt_key: ${{ secrets.DIGITALOCEAN_SSH_KEY_PRIVATE }}

      - name: Terraform Apply
        id: terraform_apply
        working-directory: terraform/scraper
        run: |
          terraform apply -auto-approve tfplan
          echo "scraper_ip=$(terraform output -raw scraper_ip)" >> $GITHUB_OUTPUT

      - name: SSH to Scraper
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.terraform_apply.outputs.scraper_ip }}
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY_PRIVATE }}
          script: |
            export PATH=$PATH:/usr/bin
            export POSTGRES_USER=$POSTGRES_USER
            export POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            export POSTGRES_HOST=$POSTGRES_HOST
            export POSTGRES_PORT=$POSTGRES_PORT
            export POSTGRES_DB=$POSTGRES_DB
            export DO_API_TOKEN=$DIGITALOCEAN_TOKEN
            apt-get update
            apt-get install -y docker.io
            docker pull registry.digitalocean.com/sendouq/scraper:latest
            docker run -d --name sendouq-scraper sendouq-scraper:latest
